# Generated by Django 4.1.4 on 2023-01-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='tile',
            new_name='title',
        ),
    ]
